# Generated by Django 4.0.5 on 2022-10-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(help_text='example@email.com', max_length=254)),
                ('full_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('interests', models.CharField(max_length=200)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user'),
        ),
    ]
